### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [tsw-apropos/qmarxantoolbox#1]
Especially in comparison with http://plugins.qgis.org/plugins/cluz/
Sorry for bothering, but we believe it is important to reduce duplication of work.
Thanks.

**Comment by aproposinfosystems** [comment]
The CLUZ plugin is a good option of one way to work with Marxan but it is a bit prescriptive and not an approach that all Marxan users want to use. I have recommended the use of CLUZ in the past but found that many Marxan users continue to use QGIS 1.8 and the old QMarxan plugin; the QMarxan Toolbox addresses this need. Fundamentally the QMarxan Toolbox takes a tool based and non-prescriptive approach and provides tools for calculating vector and raster contents of planning units in a more efficient and nuanced manner than in CLUZ or in other QGIS tools. The design of the QMarxan Toolbox also lends itself to extension to support Marxan with Zones which is an outstanding need not yet addressed for QGIS, ArcMap or R without manual scripting. In addition the QMarxan Toolbox will, by Xmas 2016, be complemented by an ArcMap equivalent for much of the processing to allow for more effective teaching of Marxan as the process will be very similar on both platforms. This last point is of particular importance to myself and other Marxan trainers because CLUZ will not be ported to ArcMap. I believe that both CLUZ and the QMarxan Toolbox are useful for QGIS and Marxan users and for the QGIS project to choose one over the other would be unwise because as far as I know nobody in the QGIS core team are Marxan experts and therefore lack the knowledge to make an assessment. Avoiding duplication is a nice goal, but hard to do when the functionality does not align completely and not always helpful as we've seen many examples of competition leading to better solutions.

**Comment by pcav** [comment]
Thanks for the detailed answer. Do you see any chance of merging the various works? I'd be happy of having a public discussion on this.

**Comment by aproposinfosystems** [comment]
I know Bob (virtually) and have been discussing with him ways of not necessarily merging but making the two tool kits more complementary. I know he is planning some updates in November and we will see how this unfolds; I suspect it will take time
